import { useState, useMemo } from '@wordpress/element';
import { MethodBadge } from './RouteItem';

// ── Helpers ─────────────────────────────────────────────────────────────────

// Shell-escape a string for inclusion in double-quoted curl argument
function shellEscape( str ) {
	return String( str )
		.replace( /\\/g, '\\\\' )
		.replace( /"/g, '\\"' )
		.replace( /`/g, '\\`' )
		.replace( /\$/g, '\\$' );
}

function buildCurl( method, path, homeUrl ) {
	const url = `${ homeUrl }${ path }`;
	return `curl -s -X ${ method } "${ shellEscape( url ) }" \\\n  -H "X-WP-Nonce: <nonce>"`;
}

async function copyToClipboard( text ) {
	if ( navigator.clipboard && navigator.clipboard.writeText ) {
		await navigator.clipboard.writeText( text );
		return;
	}
	// Fallback for older browsers / non-HTTPS
	const el = document.createElement( 'textarea' );
	el.value = text;
	el.style.position = 'fixed';
	el.style.opacity  = '0';
	document.body.appendChild( el );
	el.focus();
	el.select();
	document.execCommand( 'copy' );
	document.body.removeChild( el );
}

function downloadFile( content, filename, mime ) {
	const blob = new Blob( [ content ], { type: mime } );
	const url  = URL.createObjectURL( blob );
	const a    = document.createElement( 'a' );
	a.href     = url;
	a.download = filename;
	a.click();
	setTimeout( () => URL.revokeObjectURL( url ), 5000 );
}

function groupByNamespace( routes ) {
	return routes.reduce( ( acc, route ) => {
		const ns = route.namespace || 'core';
		( acc[ ns ] = acc[ ns ] || [] ).push( route );
		return acc;
	}, {} );
}

const ucfirst = ( s ) => ( s ? s.charAt( 0 ).toUpperCase() + s.slice( 1 ) : s );

// ── Markdown export ──────────────────────────────────────────────────────────

function buildMarkdown( routes, homeUrl ) {
	const byNs  = groupByNamespace( routes );
	const lines = [
		'# REST API Documentation',
		'',
		'> Generated by WordPress REST API Explorer',
		'',
	];

	for ( const [ ns, nsRoutes ] of Object.entries( byNs ) ) {
		lines.push( `## Namespace: ${ ns }`, '' );
		for ( const route of nsRoutes ) {
			for ( const ep of route.endpoints ) {
				const method = ep.methods[ 0 ];
				lines.push( `### ${ method } \`${ route.path }\``, '' );
				if ( route.description ) lines.push( route.description, '' );
				lines.push( `**Authentication:** ${ ucfirst( ep.auth_level ) }`, '' );
				if ( ep.args.length ) {
					lines.push( '| Parameter | Type | Required | Default | Description |' );
					lines.push( '|-----------|------|----------|---------|-------------|' );
					for ( const arg of ep.args ) {
						const req  = arg.required ? 'Yes' : 'No';
						const def  = arg.default !== null && arg.default !== undefined
							? `\`${ JSON.stringify( arg.default ) }\``
							: '—';
						const desc = ( arg.description || '—' ).replace( /\|/g, '\\|' );
						lines.push( `| \`${ arg.name }\` | ${ arg.type } | ${ req } | ${ def } | ${ desc } |` );
					}
					lines.push( '' );
				}
				lines.push(
					'**Example:**',
					'```bash',
					buildCurl( method, route.path, homeUrl ),
					'```',
					'',
					'---',
					''
				);
			}
		}
	}
	return lines.join( '\n' );
}

// ── Postman export ───────────────────────────────────────────────────────────

function buildPostman( routes, homeUrl ) {
	const byNs  = groupByNamespace( routes );
	const items = [];

	for ( const [ ns, nsRoutes ] of Object.entries( byNs ) ) {
		const folderItems = [];
		for ( const route of nsRoutes ) {
			for ( const ep of route.endpoints ) {
				const method = ep.methods[ 0 ];
				// Split path preserving segments; remove empty strings
				const pathParts = route.path.split( '/' ).filter( Boolean );
				const isQuery   = [ 'GET', 'DELETE' ].includes( method );
				const query     = isQuery
					? ep.args.map( ( a ) => ( {
							key:         a.name,
							value:       a.default !== null && a.default !== undefined ? String( a.default ) : '',
							description: a.description || '',
							disabled:    ! a.required,
					  } ) )
					: [];
				const body = ! isQuery && ep.args.length
					? {
							mode: 'raw',
							raw:  JSON.stringify(
								ep.args.reduce( ( o, a ) => {
									o[ a.name ] = a.default !== null && a.default !== undefined ? a.default : '';
									return o;
								}, {} ),
								null,
								2
							),
							options: { raw: { language: 'json' } },
					  }
					: undefined;

				const item = {
					name: `${ method } ${ route.path }`,
					request: {
						method,
						header: [ { key: 'X-WP-Nonce', value: '{{nonce}}', type: 'text' } ],
						url: {
							raw:   `{{base_url}}${ route.path }`,
							host:  [ '{{base_url}}' ],
							path:  pathParts,
							query,
						},
					},
				};
				if ( route.description ) item.request.description = route.description;
				if ( body ) item.request.body = body;
				folderItems.push( item );
			}
		}
		items.push( { name: ns, item: folderItems } );
	}

	return {
		info: {
			name:        'WordPress REST API',
			description: 'Generated by WordPress REST API Explorer',
			schema:      'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
		},
		item:     items,
		variable: [
			{ key: 'base_url', value: homeUrl, type: 'string' },
			{ key: 'nonce',    value: '',       type: 'string' },
		],
	};
}

// ── Component ────────────────────────────────────────────────────────────────

export default function DocsPanel( { routes, homeUrl, toast } ) {
	const [ search, setSearch ]     = useState( '' );
	const [ nsFilter, setNsFilter ] = useState( '' );
	const [ copiedKey, setCopied ]  = useState( null );
	const [ exporting, setExporting ] = useState( null ); // 'markdown'|'postman'|null

	const namespaces = useMemo(
		() => [ ...new Set( routes.map( ( r ) => r.namespace ) ) ].sort(),
		[ routes ]
	);

	const filtered = useMemo( () => {
		const q = search.toLowerCase();
		return routes.filter( ( r ) => {
			if ( nsFilter && r.namespace !== nsFilter ) return false;
			if ( q && ! r.path.toLowerCase().includes( q ) ) return false;
			return true;
		} );
	}, [ routes, search, nsFilter ] );

	const grouped = useMemo( () => groupByNamespace( filtered ), [ filtered ] );

	const copyCurl = async ( method, path ) => {
		const key  = path + method;
		const text = buildCurl( method, path, homeUrl );
		try {
			await copyToClipboard( text );
			setCopied( key );
			setTimeout( () => setCopied( null ), 1500 );
		} catch {
			toast?.error( 'Could not copy to clipboard — try selecting text manually.' );
		}
	};

	const exportMarkdown = async () => {
		setExporting( 'markdown' );
		try {
			const content = buildMarkdown( routes, homeUrl );
			downloadFile( content, 'api-docs.md', 'text/markdown' );
		} catch {
			toast?.error( 'Markdown export failed — check the browser console for details.' );
		} finally {
			setExporting( null );
		}
	};

	const exportPostman = async () => {
		setExporting( 'postman' );
		try {
			const json = JSON.stringify( buildPostman( routes, homeUrl ), null, 2 );
			downloadFile( json, 'api-collection.postman_collection.json', 'application/json' );
		} catch {
			toast?.error( 'Postman export failed — check the browser console for details.' );
		} finally {
			setExporting( null );
		}
	};

	return (
		<div className="rae-fullpanel">
			<div className="rae-fullpanel__header">
				<div className="rae-fullpanel__title">
					<h2>Documentation</h2>
					<span className="rae-badge">{ routes.length } routes</span>
				</div>
				<div className="rae-docs-exports">
					<button
						className="rae-btn rae-btn--secondary rae-btn--sm"
						onClick={ exportMarkdown }
						disabled={ !! exporting }
						type="button"
					>
						{ exporting === 'markdown' ? 'Exporting…' : '↓ Markdown' }
					</button>
					<button
						className="rae-btn rae-btn--secondary rae-btn--sm"
						onClick={ exportPostman }
						disabled={ !! exporting }
						type="button"
					>
						{ exporting === 'postman' ? 'Exporting…' : '↓ Postman' }
					</button>
				</div>
			</div>

			<div className="rae-fullpanel__filters">
				<input
					type="search"
					className="rae-search"
					placeholder="Filter routes…"
					value={ search }
					onChange={ ( e ) => setSearch( e.target.value ) }
					aria-label="Filter routes"
				/>
				<select
					className="rae-select"
					value={ nsFilter }
					onChange={ ( e ) => setNsFilter( e.target.value ) }
					aria-label="Filter by namespace"
				>
					<option value="">All Namespaces</option>
					{ namespaces.map( ( ns ) => (
						<option key={ ns } value={ ns }>{ ns }</option>
					) ) }
				</select>
			</div>

			{ filtered.length === 0 ? (
				<div className="rae-fullpanel__empty">
					{ routes.length === 0 ? 'No routes available.' : 'No routes match your filter.' }
				</div>
			) : (
				<div className="rae-docs-content">
					{ Object.entries( grouped ).map( ( [ ns, nsRoutes ] ) => (
						<section key={ ns } className="rae-docs-ns">
							<h3 className="rae-docs-ns__title">{ ns }</h3>

							{ nsRoutes.map( ( route ) =>
								route.endpoints.map( ( ep, i ) => {
									const method  = ep.methods[ 0 ];
									const curlKey = route.path + method;
									return (
										<div key={ `${ route.path }-${ i }` } className="rae-docs-route">
											<div className="rae-docs-route__header">
												<MethodBadge method={ method } />
												<code className="rae-docs-route__path">{ route.path }</code>
												{ route.description && (
													<span className="rae-docs-route__desc">{ route.description }</span>
												) }
											</div>

											{ ep.args.length > 0 && (
												<table className="rae-args-table rae-docs-route__args">
													<thead>
														<tr>
															<th>Parameter</th>
															<th>Type</th>
															<th>Required</th>
															<th>Default</th>
															<th>Description</th>
														</tr>
													</thead>
													<tbody>
														{ ep.args.map( ( arg ) => (
															<tr key={ arg.name }>
																<td><code>{ arg.name }</code></td>
																<td><code>{ arg.type }</code></td>
																<td>{ arg.required ? 'Yes' : 'No' }</td>
																<td>
																	{ arg.default !== null && arg.default !== undefined
																		? <code>{ JSON.stringify( arg.default ) }</code>
																		: <span className="rae-muted">—</span>
																	}
																</td>
																<td>{ arg.description || <span className="rae-muted">—</span> }</td>
															</tr>
														) ) }
													</tbody>
												</table>
											) }

											<div className="rae-docs-route__curl">
												<pre className="rae-code rae-code--sm">{ buildCurl( method, route.path, homeUrl ) }</pre>
												<button
													className="rae-btn rae-btn--secondary rae-btn--sm"
													onClick={ () => copyCurl( method, route.path ) }
													type="button"
													aria-label={ `Copy curl command for ${ method } ${ route.path }` }
												>
													{ copiedKey === curlKey ? '✓ Copied' : 'Copy' }
												</button>
											</div>
										</div>
									);
								} )
							) }
						</section>
					) ) }
				</div>
			) }
		</div>
	);
}
