<?php

namespace RestApiExplorer\Rest;

use RestApiExplorer\Admin\RouteDiscovery;

class ExportController {

	private const NAMESPACE = 'rest-api-explorer/v1';

	public static function register(): void {
		register_rest_route(
			self::NAMESPACE,
			'/export',
			[
				'methods'             => \WP_REST_Server::READABLE,
				'callback'            => [ self::class, 'handle' ],
				'permission_callback' => static fn () => current_user_can( 'manage_options' ),
				'args'                => [
					'format' => [
						'type'     => 'string',
						'enum'     => [ 'markdown', 'postman' ],
						'required' => true,
					],
				],
			]
		);
	}

	public static function handle( \WP_REST_Request $request ): \WP_REST_Response {
		$format   = $request->get_param( 'format' );
		$routes   = RouteDiscovery::get_routes();
		$home_url = home_url( '/wp-json' );

		if ( 'markdown' === $format ) {
			return new \WP_REST_Response(
				[
					'content'  => self::to_markdown( $routes, $home_url ),
					'filename' => 'api-docs.md',
				],
				200
			);
		}

		return new \WP_REST_Response(
			[
				'content'  => self::to_postman( $routes, $home_url ),
				'filename' => 'api-collection.postman_collection.json',
			],
			200
		);
	}

	private static function to_markdown( array $routes, string $home_url ): string {
		$by_ns = self::group_by_namespace( $routes );

		$lines = [
			'# REST API Documentation',
			'',
			'> Generated by WordPress REST API Explorer — ' . get_bloginfo( 'name' ),
			'',
		];

		foreach ( $by_ns as $ns => $ns_routes ) {
			$lines[] = "## Namespace: $ns";
			$lines[] = '';

			foreach ( $ns_routes as $route ) {
				foreach ( $route['endpoints'] as $endpoint ) {
					$method = $endpoint['methods'][0];
					$lines[] = "### $method {$route['path']}";
					$lines[] = '';

					if ( $route['description'] ) {
						$lines[] = $route['description'];
						$lines[] = '';
					}

					$lines[] = '**Authentication:** ' . ucfirst( $endpoint['auth_level'] );
					$lines[] = '';

					if ( ! empty( $endpoint['args'] ) ) {
						$lines[] = '| Parameter | Type | Required | Default | Description |';
						$lines[] = '|-----------|------|----------|---------|-------------|';
						foreach ( $endpoint['args'] as $arg ) {
							$required = $arg['required'] ? 'Yes' : 'No';
							$default  = $arg['default'] !== null ? '`' . json_encode( $arg['default'] ) . '`' : '—';
							$desc     = $arg['description'] ?: '—';
							$type     = is_array( $arg['type'] ) ? implode( '|', $arg['type'] ) : (string) $arg['type'];
							$lines[]  = "| `{$arg['name']}` | {$type} | $required | $default | $desc |";
						}
						$lines[] = '';
					}

					$curl    = "curl -s -X $method \"{$home_url}{$route['path']}\" \\";
					$curl   .= "\n  -H \"X-WP-Nonce: <nonce>\"";
					$lines[] = '**Example:**';
					$lines[] = '```bash';
					$lines[] = $curl;
					$lines[] = '```';
					$lines[] = '';
					$lines[] = '---';
					$lines[] = '';
				}
			}
		}

		return implode( "\n", $lines );
	}

	private static function to_postman( array $routes, string $home_url ): array {
		$by_ns = self::group_by_namespace( $routes );
		$items = [];

		foreach ( $by_ns as $ns => $ns_routes ) {
			$folder_items = [];

			foreach ( $ns_routes as $route ) {
				foreach ( $route['endpoints'] as $endpoint ) {
					$method     = $endpoint['methods'][0];
					$path_parts = array_values( array_filter( explode( '/', $route['path'] ) ) );

					$query = [];
					if ( in_array( $method, [ 'GET', 'DELETE' ], true ) ) {
						foreach ( $endpoint['args'] as $arg ) {
							$query[] = [
								'key'         => $arg['name'],
								'value'       => $arg['default'] !== null ? (string) json_encode( $arg['default'] ) : '',
								'description' => $arg['description'] ?: '',
								'disabled'    => ! $arg['required'],
							];
						}
					}

					$folder_items[] = [
						'name'    => "$method {$route['path']}",
						'request' => [
							'method'      => $method,
							'header'      => [
								[
									'key'   => 'X-WP-Nonce',
									'value' => '{{nonce}}',
									'type'  => 'text',
								],
							],
							'url'         => [
								'raw'   => "{{base_url}}{$route['path']}",
								'host'  => [ '{{base_url}}' ],
								'path'  => $path_parts,
								'query' => $query,
							],
							'description' => $route['description'] ?: '',
						],
					];
				}
			}

			$items[] = [
				'name' => $ns,
				'item' => $folder_items,
			];
		}

		return [
			'info'     => [
				'name'        => get_bloginfo( 'name' ) . ' REST API',
				'_postman_id' => wp_generate_uuid4(),
				'description' => 'Generated by WordPress REST API Explorer',
				'schema'      => 'https://schema.getpostman.com/json/collection/v2.1.0/collection.json',
			],
			'item'     => $items,
			'variable' => [
				[ 'key' => 'base_url', 'value' => $home_url, 'type' => 'string' ],
				[ 'key' => 'nonce', 'value' => '', 'type' => 'string' ],
			],
		];
	}

	private static function group_by_namespace( array $routes ): array {
		$by_ns = [];
		foreach ( $routes as $route ) {
			$ns           = $route['namespace'] ?: 'core';
			$by_ns[ $ns ][] = $route;
		}
		return $by_ns;
	}
}
